### PR TITLE
Add dSRE context for accessing GCS

### PR DESCRIPTION
**Pull request by chelseatroy**
### Goal(s) of this Pull Request:

-

### Example of how it works:

...

### Acceptance criteria:

In order to approve, reviewer must be able to...

- [x] ...

### CODE REVIEW

**Comment by whd** [comment]
I hope all you need to do to get this to work is switch `mozdata-tmp` for `moz-fx-data-circleci-tests-mozmlops` introduced in https://github.com/mozilla-services/cloudops-infra/pull/5703. If it still doesn't work I will investigate.

**Comment by chelseatroy** [comment]
force push to un-typo commit message

**Comment by whd** [comment]
I halfway expected this would happen so I mentioned it on https://github.com/mozilla-services/cloudops-infra/pull/5703#issue-2338205867. I've [updated](https://github.com/mozilla-services/cloudops-infra/pull/5703/commits/a37088f62cd53d90de1ef1793500a2fa98b8b2d4) the permissions to use the legacy role which should hopefully fix it if you re-run CI (I don't have access).

**Comment by chelseatroy** [comment]
@whd YYYYEEEEEEEEEEEEEEEESSSSSSSSSSSSS!!!

image

**Review by Dexterp37 — APPROVED** [review]

**Pull request merged**
